### ISSUE TITLE
Configuration hardcodes paths in /usr/share/

### ISSUE THREAD

**Issue by ferdnyc** [OpenPrinting/cpdb-backend-cups#15]
The `configure.ac` file currently hardcodes two values to paths in `/usr/`:

https://github.com/OpenPrinting/cpdb-backend-cups/blob/03ac1f79077a60ae36c01e8383e15906739601dc/configure.ac#L29-L36

This stems, in part, from a related issue with the `cpdb-libs` project: It hardcodes that same `/usr/share/print-backends` path as its `CPDB_DBUS_DIR` in the `cpdb-frontend.h` header. (I admit I'm not entirely clear on how the `CPDB_BACKEND_DIR` path (set to `$libdir/print-backends`) is meant to be handled, since that path doesn't appear anywhere in the `cpdb-libs` code or configuration. Perhaps frontends are meant to hardcode it to the same value?)

The problems here are twofold:

1. System paths should never be hardcoded, they should be configurable under the `prefix` value set by autoconf. Specifically, `$datadir/print-backends` can be used as the shared data path, the same way `$libdir/print-backends` is used as the backend install dir.

1. If a directory path needs to be consistent between a `cpdb-libs` build and the backend, it should not be configured to any arbitrary value in the backend `configure.ac` file (even one that uses `$datadir`/`$libdir`), it should be provided _by_ the library install via its `pkgconfig` data, and queried in the backend configuration so that the values align.

An example of the latter can be seen in the installed `dbus-1.pc` file from a dbus build, which provides locations for all of its data directories. Including the path to `${datadir}/dbus-1/services`, which can be queried from its `session_bus_services_dir` variable:

```sh
$ pkg-config --variable=session_bus_services_dir dbus-1
/usr/share/dbus-1/services
```

Such a query should replace the hardcoded `DBUS_SERVICES_DIR`. pkg-config variables can be queried from autoconf using the [`PKG_CHECK_VAR` macro](https://autotools.info/pkgconfig/variables.html), i.e.

```m4
dnl Not technically necessary, PKG_CHECK_VAR will look up the module
PKG_CHECK_MODULES([DBUS], [dbus-1])

dnl Get session bus path for linked dbus implementation
AC_MSG_CHECKING([dbus service file path])
PKG_CHECK_VAR([DBUS_SERVICES_DIR], [dbus-1], [session_bus_services_dir],
  AC_MSG_RESULT($DBUS_SERVICES_DIR),
  AC_MSG_FAILURE([cannot locate session_bus_services_dir])
)
```

By the same token, if cpdb-libs' installed `cpdb-backend.pc` file were to be expanded with `info_dir` and `backend_dir` variables (based on `${datadir}` and `${libdir}` respectively, which are in turn based on `${prefix}`), then they could be queried using `PKG_CHECK_VAR([CPDB_INFO_DIR], [cpdb-backend], [info_dir])` and `PKG_CHECK_VAR([CPDB_BACKEND_DIR], [cpdb-backend], [backend_dir])` in the backends' configuration, eliminating the need for hardcoding.

**Comment by tillkamppeter** [comment]
Fixed via pull request #17.
